services:
  - type: web
    name: blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
